// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL6uTprGBRcvA9cSKpHzJZ5wkvewbPNf8',
    appId: '1:814142370478:web:2cf3319f4719d54d3bb33f',
    messagingSenderId: '814142370478',
    projectId: 'wise-gadget-362820',
    authDomain: 'wise-gadget-362820.firebaseapp.com',
    storageBucket: 'wise-gadget-362820.appspot.com',
    measurementId: 'G-8W4K27L095',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDTrvcYQb3_V_ecuBLSzxMGhReBZixooMM',
    appId: '1:814142370478:android:41aa8960608116263bb33f',
    messagingSenderId: '814142370478',
    projectId: 'wise-gadget-362820',
    storageBucket: 'wise-gadget-362820.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL08FZMOxy1aDZ8sLuVRs6PlJaRjXb7Z8',
    appId: '1:814142370478:ios:aeef6d21284e38e63bb33f',
    messagingSenderId: '814142370478',
    projectId: 'wise-gadget-362820',
    storageBucket: 'wise-gadget-362820.appspot.com',
    androidClientId: '814142370478-t41k0u9lmhc3r2renvi4livq9ahgegj7.apps.googleusercontent.com',
    iosClientId: '814142370478-mhssvitj4n7qhrvp450souj5qhlmqbqb.apps.googleusercontent.com',
    iosBundleId: 'com.example.zoomCloneTutorial',
  );
}
